version: '3.9'
services:
  centrifugo:
    image: centrifugo/centrifugo:v6
    ports:
      - "8000:8000"
    volumes:
      - ./centrifugo.json:/centrifugo/config.json
    command: centrifugo -c config.json
    restart: unless-stopped
